### ISSUE TITLE
Transaction never completed in remove_permission_from_group

### ISSUE THREAD

**Issue by tookig** [steve-goodwin/ion_auth_acl#1]
In the `ion_auth_acl_model`, the `remove_permission_from_group `method starts a transaction that is never completed, so the query doesn't complete.

Probably easiest not to use a transaction here at all.

**Comment by MedwaySteve** [comment]
Thanks for your comment, I shall take a look into this when I get a moment. I've been working away.

**Comment by steve-goodwin** [comment]
This has now been resolved, i've kept with the transaction architecture as its what Ion Auth follows and therefore makes this a fairly similar plugin to enhance Ion Auths basic functionality.
